### ISSUE TITLE
Program exiting before unlock is unrecoverable without manual intervention.

### ISSUE THREAD

**Issue by crodwell** [cirello-io/pglock#103]
Unless I'm using it wrong - If my program exits before `lock.Close()` is called the row stays forever and any other nodes cannot ever recover without deleting the row from lock table manually.. I had expected some sort of TTL or something as a feature with the heartbeat.

For anyone else with the same problem, I found pg advisory locks to be a lot more useful as they terminate automatically when connection closes
with pgxv5: 
```
var result bool
if err := db.QueryRow(context.Background(), fmt.Sprintf("SELECT pg_try_advisory_lock(%d)", 1)).Scan(&result); err != nil {
    return err
}

if !result {
    fmt.Println("Another node has the lock.")
} else {
     fmt.Println("Obtained lock.")
}


db.Exec(context.Background(), fmt.Sprintf("SELECT pg_advisory_unlock(%d)", 1))
```

**Comment by ucirello** [comment]
Advisory locks are a great choice. I am glad you handled your situation using them.

Typically, clients competing for the same lock will wait for the lease duration before grabbing the lock again.
