### ISSUE TITLE
`FailIfLocked()` disables checking if the lock is expired

### ISSUE THREAD

**Issue by th0th** [cirello-io/pglock#122]
Here is the case:

1. A lock gets created by function, but that process somehow terminates abruptly, not able to clear the lock.
2. When another process tries to obtain the lock with the `pglock.FailIfLocked()` option, it gets `ErrNotAcquired` "cannot acquire lock", even if the lock is expired.

This doesn't happen without `pglock.FailIfLocked()` option. I assumed even if the `FailIfLocked` option is used, the expired lock should be ignored, but it's not. Is this intended behavior?

**Comment by ucirello** [comment]
hi @th0th -- thank you for this issue. 

`FailIfLocked` behavior is indeed the intended one, which also makes it incompatible with `KeepOnRelease`. `FailIfLocked` provides an immediate response to the fact that a lock (stale or not) is present, and allows you to react in different terms than just running down the clock.

**Comment by th0th** [comment]
Got it, thanks for the explanation.

Do you have a suggestion for my use case? I am trying to use lock for a periodic job that runs every 10 seconds. What I need to do is, when the function has started to run, it needs to check if the previous one is done, if not, it should cancel. I don't want to wait for the lock since there will be another run after 10 seconds, otherwise the runs wile pile up.

**Comment by ucirello** [comment]
You should probably keep the state of your application out of the lock management. But, if you really need it, one option would be to `Get()` the lock before trying to grab it.
