### ISSUE TITLE
relation "locks" does not exist

### ISSUE THREAD

**Issue by Skarlso** [cirello-io/pglock#20]
Hello!

I stumbled upon this library and would like to use it but find no description about how to setup the PSQL and I see nothing about what this mirrors and where or a documentation or anything. :)

So now, when I'm trying to use it, I'm getting this error:

```
pq: relation "locks" does not exist
```

I already figured out that it needs a locks_rvn sequence, but I have no idea what kind of locks relation it requires.

Cheers.

**Comment by Skarlso** [comment]
I see. So there is CreateTable which sets up things.

Can you please include that into the readme? :) Please? :)

**Comment by ucirello** [comment]
@Skarlso thanks for the report. I updated the README.md accordingly.

**Comment by Skarlso** [comment]
Wonderful! Thanks! <3
