### ISSUE TITLE
Support for pgx

### ISSUE THREAD

**Issue by Sh4d1** [cirello-io/pglock#21]
Hello, 
We use GORM, and since v2, gorm now uses http://github.com/jackc/pgx which is not the pq that glock supports. Could it be possible to support pgx?

**Comment by ucirello** [comment]
@Sh4d1 - you can use the UnsafeNew call for what you want. As long as it is a `database/sql` compatible driver implementation (which pgx is), you should be good to go.

https://pkg.go.dev/cirello.io/pglock#UnsafeNew

**Comment by Sh4d1** [comment]
Ah nice! Thanks, will try 😄
