### ISSUE TITLE
Heartbeat not retried in case of errors

### ISSUE THREAD

**Issue by andreaciri** [cirello-io/pglock#40]
As of today the [storeHeartbeat](https://github.com/cirello-io/pglock/blob/master/client.go#L384) method is wrapped inside a retry mechanism. However, any kind of error happening during the `storeHeartbeat` is going to immediately flag the lock as released, [skipping](https://github.com/cirello-io/pglock/blob/master/client.go#L395-L397) all the subsequent retries.

I think that in general the lock shouldn't be released in case of errors so that the heartbeat can be retried. This is useful for all transient errors like network errors or serialization errors from postgres.

I think it's safe to keep releasing the lock when the affected rows count is zero ([here](https://github.com/cirello-io/pglock/blob/8716e2a5e7161238bd1bba1e388aec08b601f695/client.go#L430)).

**Comment by ucirello** [comment]
Thanks for opening this issue, and bringing this matter to me. It took me a bit of thinking to understand the consequences of what you said, and it seems your suggestion is sensible. I incorporated your suggestions, but I will wait a little before making a release to gather more feedback from more people.
