### ISSUE TITLE
Hearbeat not working when using AcquireContext

### ISSUE THREAD

**Issue by Sh4d1** [cirello-io/pglock#5]
Hello,

I think that when I try to `AcquireContext` with a small context timeout (~10s) and the lock have to be held for at leat 1m. This is because the hearbeat goroutine uses the context from `AcquireContext` thus leading to the context to expire fast. I think it will be better to use a `context.Background()` for the hearbeat goroutine. @ucirello what do you think?

**Comment by ucirello** [comment]
The documentation should help you there: https://godoc.org/cirello.io/pglock#Client.AcquireContext
```
AcquireContext attempts to grab the lock with the given key name, wait until it succeeds or the context is done. It returns ErrNotAcquired if the context is canceled before the lock is acquired.
```

Using `AcquireContext` with a timeout smaller than your target release lock is a valid choice, but not might be what you want. Increase your context timeout or use manual cancelation. 

If you are going to use `context.Background()`, then just use `Acquire`:
https://github.com/cirello-io/pglock/blob/da19fea0d0896d9b2d8c2ec9220064073c8b5b87/client.go#L139-L141

**Comment by Sh4d1** [comment]
@ucirello just to be clear, setting a timeout on AcquireContext, also cancels the heartbeat after the context timeout I think, is this a desired behaviour?

**Comment by ucirello** [comment]
> is this a desired behaviour?

yes - I intended for it to work this way. You can use SendHeartbeat if you end up using a timeout based context as the first argument to `AcquireContext`.

What I often see when people point this characteristic of the library is that what they want instead is `Do` (https://godoc.org/cirello.io/pglock#Client.Do) -- it is going to hold the lock, execute the code inside Do under a lock, and if the context is canceled the whole clean up happens - lock, heartbeats, and code depending on the lock

**Comment by Sh4d1** [comment]
Hmm not sure if it would work. My use case:
- Acquire the lock (wait for 2 times the hearbeat, if another worker has for instance crahed holding the lock)
- Execute a "long" function (between 1-2 minutes)

So I have different timeouts for the lock and the execution. I guess I'll have to either `Acquire` with a custom cancel, or `AciqureContext` while sending the Hearbeats myself. No other solutions?

**Comment by ucirello** [comment]
I might be losing something here, but you only need the long function timeout based context. If the heartbeat frequency is smaller than the long function timeout, all you need is one context with the long function timeout and use `Do` with it.

```
const LongFunctionTimeoutPlusFudge = LongFunctionTimeout + Heartbeat*2
ctx, cancel := context.WithTimeout(ctx, LongFunctionTimeoutPlusFudge)
err = c.Do(ctx, name, func(ctx context.Context, l *pglock.Lock) error {
	for {
		if ctx.Err() != nil {
				return ctx.Err()
		}
		// your logic goes here
	}
})
```

**Comment by Sh4d1** [comment]
But in this case, the `Do` will wait on the `Acquire` for `LongFunctionTimeoutPlusFudge` before return an error if it's already locked. My use case relies on the function to just wait for 2 hearbeat in order to:
- either get the lock
- or "quickly" ignore if the lock is already held

**Comment by ucirello** [comment]
I see your point. If you don't want to wait for the locking failure, then probably you want to use `FailIfLocked` (https://godoc.org/cirello.io/pglock#FailIfLocked)

**Comment by Sh4d1** [comment]
@ucirello  That what I did at first, but if a worker crashes while holding the lock, it's a bit annoying since it doesnt get the lock even if the hearbeat is outdated. This is due to https://github.com/cirello-io/pglock/blob/master/client.go#L226 and https://github.com/cirello-io/pglock/blob/master/client.go#L147 
Thus when `Acquire` is called with `FailIfLocked` and if the lock already exists and is outdated, it will always fail. This may be an issue I think btw

**Comment by ucirello** [comment]
@Sh4d1 - see your point. I am reopening this issue. In any case, add a lock option with a custom heartbeat context won't hurt.

**Comment by ucirello** [comment]
@Sh4d1 - Please upgrade to https://github.com/cirello-io/pglock/releases/tag/v1.7.0

**Comment by Sh4d1** [comment]
That was quick! Thanks @ucirello I'll try that next week 😁

**Comment by Sh4d1** [comment]
@ucirello So apprently it does not fix the issue, since https://github.com/cirello-io/pglock/blob/master/client.go#L178 still use the context given to `AcquireContext`

**Comment by ucirello** [comment]
weird - I thought I had commited the line here - I am sorry. Taking a look.

**Comment by ucirello** [comment]
@Sh4d1 could you please test https://github.com/cirello-io/pglock/releases/tag/v1.7.1

**Comment by Sh4d1** [comment]
@ucirello I'll try to give it a try tomorrow!

**Comment by Sh4d1** [comment]
@ucirello sorry forgot to update you, but it's now working as expected :tada:
