### ISSUE TITLE
Introduce configurable logging levels

### ISSUE THREAD

**Issue by slonka** [cirello-io/pglock#55]
Hi all! 

Some of the logs in this library are quite noisy in our system (e.g. `storeAcquire in/out` was logged 1.8M times last week). Is this normal or out of the ordinary? If normal, would you be open for a contribution to introduce logging levels to the logger package?

Best regards

**Comment by ucirello** [comment]
I am waiting for `https://pkg.go.dev/log/slog@master` to be released so that I can tune the log levels internally. Hopefully soon. Just waiting for the Go core team to finish Go 1.21 release.

**Comment by slonka** [comment]
It's awesome that it's fixed, can we get a release out so we can use it?

**Comment by ucirello** [comment]
Released! https://github.com/cirello-io/pglock/releases/tag/v1.14.0
