### ISSUE TITLE
Create Sequence Fails

### ISSUE THREAD

**Issue by yungtrizzle** [cirello-io/pglock#64]
Setting up the migration for pglocks but my db rejects the migration with ` ERROR: sequence must have same owner as table it is linked to (SQLSTATE 55000)` 

My migration 
```sql
-- +goose Up
CREATE TABLE dif_kin_locks (
	name CHARACTER VARYING(255) PRIMARY KEY,
	record_version_number BIGINT,
	data BYTEA,
	owner CHARACTER VARYING(255)
);

CREATE SEQUENCE dif_kin_locks_rvn CYCLE OWNED BY dif_kin_locks.record_version_number;

-- +goose Down
DROP TABLE fdi_ikn_locks;
DROP SEQUENCE IF EXISTS fdi_ikn_locks_rvn;
```

The failure happens with Postgres 15.4.
On my local machine I have 15.4 as well and can't reproduce 🤷🏾‍♂️

**Comment by yungtrizzle** [comment]
By the way, Is it necessary to have the sequence owned? Can it be owned by none? Seems the only advantage comes at dropping the table.

**Comment by ucirello** [comment]
The sequence doesn't need the owner to work. But I added it because it helps with people not forgetting DB artifacts around.

**Comment by yungtrizzle** [comment]
> The sequence doesn't need the owner to work. But I added it because it helps with people not forgetting DB artifacts around.

Ahh I see. Thanks
