### ISSUE TITLE
Support for `pgxpool`?

### ISSUE THREAD

**Issue by disq** [cirello-io/pglock#82]
Hi,

Great project. I was wondering if there will be support for `pgxpool.Pool` or other postgres "connectors" in the future. Having `*sqldb.DB` as the only acceptable form of database really blocks things in that regard, where the codebase really doesn't need `sql.DB` specifically. It also goes against Go's "Accept interfaces, return structs" proverb.

**Comment by ucirello** [comment]
Or even more precisely, why not use Go's database/sql/driver package itself? 

Refer to https://pkg.go.dev/database/sql/driver#Connector

**Comment by ucirello** [comment]
Have you considered using the package stdlib adapter itself?

<img width="472" alt="image" src="https://github.com/cirello-io/pglock/assets/138827/e7c39791-afa8-4581-858d-27a2498e64b2">

Refer to https://pkg.go.dev/github.com/jackc/pgx/v5/stdlib

**Comment by disq** [comment]
Using [pgxpool.Acquire](https://pkg.go.dev/github.com/jackc/pgx/v5/pgxpool#Pool.Acquire) directly won't work because the returned [Conn](https://pkg.go.dev/github.com/jackc/pgx/v5/pgxpool#Conn) is not compatible with `sql.DB`, due to the methods it implements mainly returns pgx-internal structs.

`stdlib` is a gem, I'll take a look and it might actually solve my issue.

The lack of `rollback` in some 'artificial' error cases (the one where it returns `return ErrNotAcquired` but keeping the tx open comes to mind, might be more) seems like a real bug and I'll open a separate issue/PR for those.

Thanks for the detailed discussion.

**Comment by disq** [comment]
Yup works, all good!

**Comment by crodwell** [comment]
I couldn't get this to work with pgx v5 pool, pglock returns

`cannot create lock client:this is not a PostgreSQL connection`

**Comment by crodwell** [comment]
Never mind, found the solution.. For anyone else looking there is a another func that doesn't check the driver and works with pgxpool.

```
	c, err := pglock.UnsafeNew(stdlib.OpenDBFromPool(pgxPoolConn))
```
