### ISSUE TITLE
Don't log missed heartbeat as error when context is canceled

### ISSUE THREAD

**Issue by bartsmykla** [cirello-io/pglock#92]
We are encountering the following error message in our logs:

```
heartbeat missed: cannot send heartbeat (kuma-cp-lock): context canceled
```

This error appears intermittently and, based on our understanding, should not be classified as an error. We believe it's safe to suppress the logging of this message.

We are considering contributing a change to the codebase that would prevent these messages from being logged as errors. We would like to hear your thoughts on this approach and any potential considerations before proceeding.

**Comment by ucirello** [comment]
@bartsmykla -- thanks for opening this issue and bringing up this topic. I think I understand where you are coming from. Namely, if the context had been checked just before the heartbeat, it would not have been logged.

I appreciate your PR, but I am going to try a slightly different solution.

**Comment by bartsmykla** [comment]
Sgtm. Thanks for taking care of it. Do you think you could release the new version of `pglock` with this change?

**Comment by ucirello** [comment]
@bartsmykla on it
